import { CatalogItem } from './types';

export const CATALOG: CatalogItem[] = [
  { type: 'Отделка', name: 'Rome Vein', brand: 'ABK', spec: 'Керамогранит, 120×278', unit: 'м²', price: 6500, article: 'PF60005800', format: '120 × 278 см · 6 мм', surface: 'Матовая, ректификат', color: 'Statuario' },
  { type: 'Отделка', name: 'Marvel Onyx', brand: 'Atlas Concorde', spec: 'Керамогранит, 60×120', unit: 'м²', price: 5900, article: 'AAP-MO60', format: '60 × 120 см', surface: 'Полированная', color: 'Onyx' },
  { type: 'Отделка', name: 'Microtopping', brand: 'Ideal Work', spec: 'Микроцемент, серый', unit: 'м²', price: 1000, article: 'MT-GREY', format: 'наливной', surface: 'Шёлк-матовая', color: 'Grigio' },
  { type: 'Отделка', name: 'Дуб Rustic', brand: 'Coswick', spec: 'Инженерная доска', unit: 'м²', price: 4800, article: 'CW-OAK-R', format: '1900 × 190 мм', surface: 'Матовый лак', color: 'Натуральный' },
  { type: 'Отделка', name: 'Marmorino', brand: 'San Marco', spec: 'Венецианская штукатурка', unit: 'м²', price: 1400, article: 'SM-MARM', format: 'мелкая фракция', surface: 'Полуглянец', color: 'Белый' },
  { type: 'Сантехника', name: 'Гигиенический душ', brand: 'GESSI', spec: 'Один вывод, чёрный', unit: 'шт', price: 18500, article: 'GE-31643', format: 'настенный', surface: 'Black metal', color: 'Чёрный матовый' },
  { type: 'Сантехника', name: 'Смеситель Trattaria', brand: 'Fantini', spec: 'Для раковины', unit: 'шт', price: 42000, article: 'FA-TR-01', format: 'однорычажный', surface: 'Хром', color: 'Хром' },
  { type: 'Сантехника', name: 'Унитаз ME by Starck', brand: 'Duravit', spec: 'Подвесной, безободковый', unit: 'шт', price: 34000, article: 'DU-45290900', format: 'подвесной', surface: 'Глазурь', color: 'Белый' },
  { type: 'Сантехника', name: 'Раковина Miena', brand: 'Kaldewei', spec: 'Накладная, сталь-эмаль', unit: 'шт', price: 28000, article: 'KW-MIENA', format: 'накладная', surface: 'Сталь-эмаль', color: 'Белый матовый' },
  { type: 'Мебель', name: 'Mex кресло', brand: 'Cassina', spec: 'Ткань Rohi, песочный', unit: 'шт', price: 36000, article: 'CAS-MEX', format: '78 × 80 см', surface: 'Ткань Rohi', color: 'Песочный' },
  { type: 'Мебель', name: 'Диван Soriana', brand: 'Cassina', spec: 'Модульный, кожа', unit: 'шт', price: 210000, article: 'CAS-SOR', format: 'модульный', surface: 'Кожа', color: 'Коньяк' },
  { type: 'Мебель', name: 'Стол Doge', brand: 'Cassina', spec: 'Стекло / хром', unit: 'шт', price: 145000, article: 'CAS-DOGE', format: '200 × 100 см', surface: 'Стекло', color: 'Прозрачный' },
  { type: 'Мебель', name: 'Стул Cab', brand: 'Cassina', spec: 'Кожа, чёрный', unit: 'шт', price: 62000, article: 'CAS-CAB', format: 'стандарт', surface: 'Кожа', color: 'Чёрный' },
  { type: 'Освещение', name: 'Model 2065', brand: 'Astep', spec: 'Подвес, опал + латунь', unit: 'шт', price: 31500, article: 'AST-2065', format: 'Ø 25 см', surface: 'Опал. стекло', color: 'Латунь' },
  { type: 'Освещение', name: 'Flowerpot VP1', brand: '&Tradition', spec: 'Подвес', unit: 'шт', price: 24000, article: 'AT-VP1', format: 'Ø 23 см', surface: 'Металл', color: 'Матовый белый' },
  { type: 'Освещение', name: 'Bellhop', brand: 'Flos', spec: 'Настольная, портативная', unit: 'шт', price: 19500, article: 'FL-BELL', format: 'портативная', surface: 'Полимер', color: 'Кирпичный' },
  { type: 'Освещение', name: 'IC Lights W1', brand: 'Flos', spec: 'Настенное бра', unit: 'шт', price: 33000, article: 'FL-IC-W1', format: 'Ø 20 см', surface: 'Латунь / стекло', color: 'Латунь' },
  { type: 'Текстиль', name: 'Портьеры Blackout', brand: 'Kvadrat Ready Made', spec: 'Затемняющие', unit: 'м.п.', price: 3200, article: 'KV-BLK', format: 'ширина 300 см', surface: 'Ткань', color: 'Графит' },
  { type: 'Текстиль', name: 'Ковёр Ethan Cook', brand: 'Hay', spec: 'Ручная работа, шерсть', unit: 'шт', price: 48000, article: 'HAY-EC-1', format: '200 × 300 см', surface: 'Шерсть', color: 'Мультиколор' },
  { type: 'Оборудование', name: 'Варочная панель', brand: 'Gaggenau', spec: 'Индукция, 80 см', unit: 'шт', price: 240000, article: 'GG-CI491', format: '80 см', surface: 'Стекло', color: 'Чёрный' },
  { type: 'Оборудование', name: 'Духовой шкаф', brand: 'Miele', spec: 'Combi-Steam', unit: 'шт', price: 320000, article: 'MI-DGC7', format: '60 см', surface: 'Сталь', color: 'Графит' },
  { type: 'Оборудование', name: 'Холодильник', brand: 'Liebherr', spec: 'Встраиваемый', unit: 'шт', price: 180000, article: 'LB-BUILT', format: '178 см', surface: 'Сталь', color: 'Серебристый' },
  { type: 'Инженерное оборудование', name: 'Тёплый пол', brand: 'Devi', spec: 'Мат, 150 Вт/м²', unit: 'м²', price: 2400, article: 'DV-MAT150', format: 'рулон', surface: '—', color: '—' },
  { type: 'Инженерное оборудование', name: 'Конвектор внутрипольный', brand: 'Jaga', spec: 'Mini Canal', unit: 'шт', price: 26000, article: 'JG-MINI', format: '1000 мм', surface: 'Сталь', color: 'Белый' },
];