import { CatalogItem, Project, ProjectStatus, ProjectType, SpecItem } from "./types";

export const COVER_PALETTE: string[] = [
  "bg-bg-gold",
  "bg-bg-green-light",
  "bg-bg-red-light",
  "bg-bg-select",
  "bg-bg-clear",
];

export const TYPE_COLORS: Record<ProjectType, string> = {
  Интерьер: "bg-bg-accent text-bg",
  Экстерьер: "bg-bg-green text-bg",
  Коммерческий: "bg-bg-amber text-bg",
};

export const STATUS_CONFIG: Record<
  ProjectStatus,
  { dot: string; label: string }
> = {
  "В работе": { dot: "bg-bg-green", label: "В работе" },
  Завершен: { dot: "bg-bg-accent", label: "Завершен" },
  Черновик: { dot: "bg-fg-muted", label: "Черновик" },
  "На паузе": { dot: "bg-bg-amber", label: "На паузе" },
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    name: "Резиденция на Патриарших",
    type: "Интерьер",
    status: "В работе",
    rooms: 8,
    items: 312,
    budget: 45_600_000,
    updatedAt: "2026-07-07",
  },
  {
    id: "p2",
    name: "Лофт-студия ArtPlay",
    type: "Интерьер",
    status: "Завершен",
    rooms: 3,
    items: 97,
    budget: 8_200_000,
    updatedAt: "2026-06-18",
  },
  {
    id: "p3",
    name: "Загородный дом Villa Verde",
    type: "Экстерьер",
    status: "В работе",
    rooms: 12,
    items: 548,
    budget: 78_300_000,
    updatedAt: "2026-07-05",
  },
  {
    id: "p4",
    name: "Офис TechPoint",
    type: "Коммерческий",
    status: "Черновик",
    rooms: 5,
    items: 44,
    budget: 3_150_000,
    updatedAt: "2026-06-29",
  },
  {
    id: "p5",
    name: "Пентхаус City Park",
    type: "Интерьер",
    status: "На паузе",
    rooms: 6,
    items: 203,
    budget: 34_500_000,
    updatedAt: "2026-05-14",
  },
  {
    id: "p6",
    name: "Ресторан White Rabbit",
    type: "Коммерческий",
    status: "Завершен",
    rooms: 4,
    items: 281,
    budget: 19_800_000,
    updatedAt: "2026-06-01",
  },
];

export const STORAGE_KEY = "spec_items_v1";

export const BRAND_SITES: Record<string, string> = {
  ABK: "https://www.abk.it",
  "Ideal Work": "https://www.idealwork.com",
  GESSI: "https://www.gessi.com",
  Cassina: "https://www.cassina.com",
  Astep: "https://asteplight.com",
};

export const FILE_CATS = [
  {
    key: "schemas",
    label: "Схемы",
    accept: ".pdf,.dwg,.dxf,.png,.jpg,.jpeg",
    kind: "doc" as const,
    upTitle: "Загрузить схему производителя",
    upHint: "PDF, DWG, DXF · спецлисты, узлы, чертежи",
    empty: "Чертежи, технические листы и узлы от производителя",
  },
  {
    key: "textures",
    label: "Текстуры",
    accept: "image/*,.exr,.tif,.tiff",
    kind: "tex" as const,
    upTitle: "Загрузить текстуру",
    upHint: "JPG, PNG, TIFF, EXR · карты для визуализации",
    empty: "PBR-карты для 3ds Max, Corona, V-Ray, Blender",
  },
  {
    key: "care",
    label: "Инструкции",
    accept: ".pdf,.doc,.docx,.jpg,.jpeg,.png",
    kind: "doc" as const,
    upTitle: "Загрузить инструкцию",
    upHint: "PDF, DOC · монтаж, укладка, уход",
    empty: "Инструкции по монтажу, укладке и уходу",
  },
  {
    key: "cad",
    label: "3D / CAD",
    accept: ".skp,.rfa,.3ds,.max,.obj,.fbx,.dwg",
    kind: "doc" as const,
    upTitle: "Загрузить 3D / CAD-блок",
    upHint: "SKP, RFA, MAX, 3DS, OBJ, FBX",
    empty: "Готовые блоки и модели для дизайнера",
  },
];

export const MAP_OPTIONS = [
  "Diffuse / Albedo",
  "Normal",
  "Roughness",
  "Bump",
  "Displacement",
  "Metallic",
  "AO",
  "Opacity",
  "Gloss",
];

export const SEED_ITEMS: SpecItem[] = [
  {
    id: "i1",
    type: "Отделка",
    code: "От-01",
    name: "Rome Vein",
    brand: "ABK",
    spec: "Керамогранит, 120×278",
    qty: 30,
    unit: "м²",
    price: 6500,
    status: "Не выбрано",
    article: "PF60005800",
    format: "120 × 278 см · 6 мм",
    surface: "Матовая, ректификат",
    color: "Statuario",
    variants: [
      {
        name: "Rome Vein · ABK",
        lead: "срок 4–6 недель",
        price: 6500,
        selected: true,
      },
      {
        name: "Marvel Onyx · Atlas",
        lead: "срок 2–3 недели",
        price: 5900,
        selected: false,
      },
    ],
    rooms: ["Гостиная", "Кухня-столовая", "Холл"],
    avail: "Под заказ",
    leadTime: "4–6 недель",
    manager: {
      name: "Анна Лебедева · ABK Studio",
      phone: "+7 495 120-44-90",
      email: "a.lebedeva@abk.ru",
    },
    notes:
      "Заказывать с запасом +5% на подрезку. Раскладку согласовать с прорабом до отгрузки.",
  },
  {
    id: "i2",
    type: "Отделка",
    code: "От-02",
    name: "Rome Vein",
    brand: "ABK",
    spec: "Керамогранит, 60×120",
    qty: 11,
    unit: "м²",
    price: 6500,
    status: "Подобрано",
    article: "PF60005801",
    format: "60 × 120 см · 9 мм",
    surface: "Матовая",
    color: "Statuario",
    variants: [
      {
        name: "Rome Vein · ABK",
        lead: "срок 4–6 недель",
        price: 6500,
        selected: true,
      },
    ],
  },
  {
    id: "i3",
    type: "Отделка",
    code: "От-03",
    name: "Microtopping",
    brand: "Ideal Work",
    spec: "Микроцемент, серый",
    qty: 65,
    unit: "м²",
    price: 1000,
    status: "Согласовано",
    article: "MT-GREY",
    format: "наливной",
    surface: "Шёлк-матовая",
    color: "Grigio",
    variants: [],
  },
  {
    id: "i4",
    type: "Сантехника",
    code: "С-01",
    name: "Гигиенический душ",
    brand: "GESSI",
    spec: "Один вывод, чёрный",
    qty: 2,
    unit: "шт",
    price: 18500,
    status: "Заменить",
    article: "GE-31643",
    format: "настенный",
    surface: "Black metal",
    color: "Чёрный матовый",
    variants: [
      { name: "GESSI 316", lead: "в наличии", price: 18500, selected: true },
    ],
    rooms: ["Гостевой санузел", "Постирочная"],
  },
  {
    id: "i5",
    type: "Сантехника",
    code: "С-02",
    name: "Inciso смеситель",
    brand: "GESSI",
    spec: "Настенный, хром",
    qty: 4,
    unit: "шт",
    price: 13200,
    status: "Не выбрано",
    article: "GE-58111",
    format: "настенный",
    surface: "Chrome",
    color: "Хром",
    variants: [],
    rooms: [
      "Ванная мастер",
      "Гостевой санузел",
      "Кухня-столовая",
      "Санузел детский",
    ],
  },
  {
    id: "i6",
    type: "Мебель",
    code: "М-01",
    name: "Soriana диван",
    brand: "Cassina",
    spec: "3-местный, кожа Pelle",
    qty: 1,
    unit: "шт",
    price: 340000,
    status: "Приобретено",
    article: "CAS-SOR3",
    format: "240 × 95 см",
    surface: "Кожа Pelle",
    color: "Sabbia",
    variants: [
      {
        name: "Soriana · кожа",
        lead: "срок 10–12 недель",
        price: 340000,
        selected: true,
      },
      {
        name: "Soriana · ткань",
        lead: "срок 8 недель",
        price: 268000,
        selected: false,
      },
    ],
    rooms: ["Гостиная"],
  },
  {
    id: "i7",
    type: "Мебель",
    code: "М-02",
    name: "Mex кресло",
    brand: "Cassina",
    spec: "Ткань Rohi, песочный",
    qty: 2,
    unit: "шт",
    price: 36000,
    status: "Доставлено",
    article: "CAS-MEX",
    format: "78 × 80 см",
    surface: "Ткань Rohi",
    color: "Песочный",
    variants: [],
  },
  {
    id: "i8",
    type: "Освещение",
    code: "О-01",
    name: "Model 2065",
    brand: "Astep",
    spec: "Подвес, опал + латунь",
    qty: 3,
    unit: "шт",
    price: 31500,
    status: "Не выбрано",
    article: "AST-2065",
    format: "Ø 25 см",
    surface: "Опал. стекло",
    color: "Латунь",
    variants: [
      {
        name: "Model 2065",
        lead: "срок 5 недель",
        price: 31500,
        selected: true,
      },
    ],
  },
];

export const CATALOG: CatalogItem[] = [
  {
    type: "Отделка",
    name: "Rome Vein",
    brand: "ABK",
    spec: "Керамогранит, 120×278",
    unit: "м²",
    price: 6500,
    article: "PF60005800",
    format: "120 × 278 см · 6 мм",
    surface: "Матовая, ректификат",
    color: "Statuario",
  },
  {
    type: "Отделка",
    name: "Marvel Onyx",
    brand: "Atlas Concorde",
    spec: "Керамогранит, 60×120",
    unit: "м²",
    price: 5900,
    article: "AAP-MO60",
    format: "60 × 120 см",
    surface: "Полированная",
    color: "Onyx",
  },
  {
    type: "Отделка",
    name: "Microtopping",
    brand: "Ideal Work",
    spec: "Микроцемент, серый",
    unit: "м²",
    price: 1000,
    article: "MT-GREY",
    format: "наливной",
    surface: "Шёлк-матовая",
    color: "Grigio",
  },
  {
    type: "Отделка",
    name: "Дуб Rustic",
    brand: "Coswick",
    spec: "Инженерная доска",
    unit: "м²",
    price: 4800,
    article: "CW-OAK-R",
    format: "1900 × 190 мм",
    surface: "Матовый лак",
    color: "Натуральный",
  },
  {
    type: "Отделка",
    name: "Marmorino",
    brand: "San Marco",
    spec: "Венецианская штукатурка",
    unit: "м²",
    price: 1400,
    article: "SM-MARM",
    format: "мелкая фракция",
    surface: "Полуглянец",
    color: "Белый",
  },
  {
    type: "Сантехника",
    name: "Гигиенический душ",
    brand: "GESSI",
    spec: "Один вывод, чёрный",
    unit: "шт",
    price: 18500,
    article: "GE-31643",
    format: "настенный",
    surface: "Black metal",
    color: "Чёрный матовый",
  },
  {
    type: "Сантехника",
    name: "Смеситель Trattaria",
    brand: "Fantini",
    spec: "Для раковины",
    unit: "шт",
    price: 42000,
    article: "FA-TR-01",
    format: "однорычажный",
    surface: "Хром",
    color: "Хром",
  },
  {
    type: "Сантехника",
    name: "Унитаз ME by Starck",
    brand: "Duravit",
    spec: "Подвесной, безободковый",
    unit: "шт",
    price: 34000,
    article: "DU-45290900",
    format: "подвесной",
    surface: "Глазурь",
    color: "Белый",
  },
  {
    type: "Сантехника",
    name: "Раковина Miena",
    brand: "Kaldewei",
    spec: "Накладная, сталь-эмаль",
    unit: "шт",
    price: 28000,
    article: "KW-MIENA",
    format: "накладная",
    surface: "Сталь-эмаль",
    color: "Белый матовый",
  },
  {
    type: "Мебель",
    name: "Mex кресло",
    brand: "Cassina",
    spec: "Ткань Rohi, песочный",
    unit: "шт",
    price: 36000,
    article: "CAS-MEX",
    format: "78 × 80 см",
    surface: "Ткань Rohi",
    color: "Песочный",
  },
  {
    type: "Мебель",
    name: "Диван Soriana",
    brand: "Cassina",
    spec: "Модульный, кожа",
    unit: "шт",
    price: 210000,
    article: "CAS-SOR",
    format: "модульный",
    surface: "Кожа",
    color: "Коньяк",
  },
  {
    type: "Мебель",
    name: "Стол Doge",
    brand: "Cassina",
    spec: "Стекло / хром",
    unit: "шт",
    price: 145000,
    article: "CAS-DOGE",
    format: "200 × 100 см",
    surface: "Стекло",
    color: "Прозрачный",
  },
  {
    type: "Мебель",
    name: "Стул Cab",
    brand: "Cassina",
    spec: "Кожа, чёрный",
    unit: "шт",
    price: 62000,
    article: "CAS-CAB",
    format: "стандарт",
    surface: "Кожа",
    color: "Чёрный",
  },
  {
    type: "Освещение",
    name: "Model 2065",
    brand: "Astep",
    spec: "Подвес, опал + латунь",
    unit: "шт",
    price: 31500,
    article: "AST-2065",
    format: "Ø 25 см",
    surface: "Опал. стекло",
    color: "Латунь",
  },
  {
    type: "Освещение",
    name: "Flowerpot VP1",
    brand: "&Tradition",
    spec: "Подвес",
    unit: "шт",
    price: 24000,
    article: "AT-VP1",
    format: "Ø 23 см",
    surface: "Металл",
    color: "Матовый белый",
  },
  {
    type: "Освещение",
    name: "Bellhop",
    brand: "Flos",
    spec: "Настольная, портативная",
    unit: "шт",
    price: 19500,
    article: "FL-BELL",
    format: "портативная",
    surface: "Полимер",
    color: "Кирпичный",
  },
  {
    type: "Освещение",
    name: "IC Lights W1",
    brand: "Flos",
    spec: "Настенное бра",
    unit: "шт",
    price: 33000,
    article: "FL-IC-W1",
    format: "Ø 20 см",
    surface: "Латунь / стекло",
    color: "Латунь",
  },
  {
    type: "Текстиль",
    name: "Портьеры Blackout",
    brand: "Kvadrat Ready Made",
    spec: "Затемняющие",
    unit: "м.п.",
    price: 3200,
    article: "KV-BLK",
    format: "ширина 300 см",
    surface: "Ткань",
    color: "Графит",
  },
  {
    type: "Текстиль",
    name: "Ковёр Ethan Cook",
    brand: "Hay",
    spec: "Ручная работа, шерсть",
    unit: "шт",
    price: 48000,
    article: "HAY-EC-1",
    format: "200 × 300 см",
    surface: "Шерсть",
    color: "Мультиколор",
  },
  {
    type: "Оборудование",
    name: "Варочная панель",
    brand: "Gaggenau",
    spec: "Индукция, 80 см",
    unit: "шт",
    price: 240000,
    article: "GG-CI491",
    format: "80 см",
    surface: "Стекло",
    color: "Чёрный",
  },
  {
    type: "Оборудование",
    name: "Духовой шкаф",
    brand: "Miele",
    spec: "Combi-Steam",
    unit: "шт",
    price: 320000,
    article: "MI-DGC7",
    format: "60 см",
    surface: "Сталь",
    color: "Графит",
  },
  {
    type: "Оборудование",
    name: "Холодильник",
    brand: "Liebherr",
    spec: "Встраиваемый",
    unit: "шт",
    price: 180000,
    article: "LB-BUILT",
    format: "178 см",
    surface: "Сталь",
    color: "Серебристый",
  },
  {
    type: "Инженерное оборудование",
    name: "Тёплый пол",
    brand: "Devi",
    spec: "Мат, 150 Вт/м²",
    unit: "м²",
    price: 2400,
    article: "DV-MAT150",
    format: "рулон",
    surface: "—",
    color: "—",
  },
  {
    type: "Инженерное оборудование",
    name: "Конвектор внутрипольный",
    brand: "Jaga",
    spec: "Mini Canal",
    unit: "шт",
    price: 26000,
    article: "JG-MINI",
    format: "1000 мм",
    surface: "Сталь",
    color: "Белый",
  },
];
